In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('DataGajiJateng.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['Semarang' 44.0 7200000.0]
 ['Pemalang' 48.0 4800000.0]
 ['Tegal' nan 5400000.0]
 ['Pemalang' 38.0 6100000.0]
 ['Tegal' 40.0 6400000.0]
 ['Semarang' 35.0 nan]
 ['Pemalang' 39.0 5200000.0]
 ['Semarang' 48.0 5500000.0]
 ['Tegal' 50.0 8300000.0]
 ['Semarang' 37.0 6700000.0]
 ['Pemalang' 40.0 4300000.0]
 ['Tegal' 38.0 nan]
 ['Semarang' 40.0 3400000.0]
 ['Pemalang' 34.0 nan]
 ['Semarang' nan 4900000.0]]


In [4]:
print(y)

['Belum' 'Sudah' 'Belum' 'Belum' 'Sudah' 'Sudah' 'Belum' 'Sudah' 'Belum'
 'Sudah' 'Sudah' 'Belum' 'Sudah' 'Sudah' 'Belum']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [6]:
print(X)

[['Semarang' 44.0 7200000.0]
 ['Pemalang' 48.0 4800000.0]
 ['Tegal' 40.84615384615385 5400000.0]
 ['Pemalang' 38.0 6100000.0]
 ['Tegal' 40.0 6400000.0]
 ['Semarang' 35.0 5683333.333333333]
 ['Pemalang' 39.0 5200000.0]
 ['Semarang' 48.0 5500000.0]
 ['Tegal' 50.0 8300000.0]
 ['Semarang' 37.0 6700000.0]
 ['Pemalang' 40.0 4300000.0]
 ['Tegal' 38.0 5683333.333333333]
 ['Semarang' 40.0 3400000.0]
 ['Pemalang' 34.0 5683333.333333333]
 ['Semarang' 40.84615384615385 4900000.0]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[0.0 1.0 0.0 44.0 7200000.0]
 [1.0 0.0 0.0 48.0 4800000.0]
 [0.0 0.0 1.0 40.84615384615385 5400000.0]
 [1.0 0.0 0.0 38.0 6100000.0]
 [0.0 0.0 1.0 40.0 6400000.0]
 [0.0 1.0 0.0 35.0 5683333.333333333]
 [1.0 0.0 0.0 39.0 5200000.0]
 [0.0 1.0 0.0 48.0 5500000.0]
 [0.0 0.0 1.0 50.0 8300000.0]
 [0.0 1.0 0.0 37.0 6700000.0]
 [1.0 0.0 0.0 40.0 4300000.0]
 [0.0 0.0 1.0 38.0 5683333.333333333]
 [0.0 1.0 0.0 40.0 3400000.0]
 [1.0 0.0 0.0 34.0 5683333.333333333]
 [0.0 1.0 0.0 40.84615384615385 4900000.0]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1 1 0 1 1 0]


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
print(X_train)

[[0.0 0.0 1.0 40.84615384615385 5400000.0]
 [1.0 0.0 0.0 40.0 4300000.0]
 [0.0 0.0 1.0 40.0 6400000.0]
 [1.0 0.0 0.0 48.0 4800000.0]
 [1.0 0.0 0.0 34.0 5683333.333333333]
 [0.0 1.0 0.0 44.0 7200000.0]
 [0.0 1.0 0.0 40.84615384615385 4900000.0]
 [0.0 1.0 0.0 37.0 6700000.0]
 [0.0 0.0 1.0 50.0 8300000.0]
 [0.0 1.0 0.0 40.0 3400000.0]
 [0.0 0.0 1.0 38.0 5683333.333333333]
 [0.0 1.0 0.0 35.0 5683333.333333333]]


In [13]:
print(X_test)

[[1.0 0.0 0.0 38.0 6100000.0]
 [0.0 1.0 0.0 48.0 5500000.0]
 [1.0 0.0 0.0 39.0 5200000.0]]


In [14]:
print(y_train)

[0 1 1 1 1 0 0 1 0 1 0 1]


In [15]:
print(y_test)

[0 1 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [17]:
print(X_train)

[[0.0 0.0 1.0 0.04489637563733442 -0.23989936151583452]
 [1.0 0.0 0.0 -0.14030117386667082 -1.1074806141210434]
 [0.0 0.0 1.0 -0.14030117386667082 0.5488108681252645]
 [1.0 0.0 0.0 1.6106574759893777 -0.713125499300494]
 [1.0 0.0 0.0 -1.4535201612587072 -0.016431463117523387]
 [0.0 1.0 0.0 0.7351781510613534 1.1797790518381437]
 [0.0 1.0 0.0 0.04489637563733442 -0.634254476336384]
 [0.0 1.0 0.0 -0.796910667562689 0.7854239370175942]
 [0.0 0.0 1.0 2.0483971384533897 2.0473603044433526]
 [0.0 1.0 0.0 -0.14030117386667082 -1.8173198207980326]
 [0.0 0.0 1.0 -0.5780408363306829 -0.016431463117523387]
 [0.0 1.0 0.0 -1.234650330026701 -0.016431463117523387]]


In [18]:
print(X_test)

[[1.0 0.0 0.0 -0.5780408363306829 0.3121977992329348]
 [0.0 1.0 0.0 1.6106574759893777 -0.16102833855172463]
 [1.0 0.0 0.0 -0.3591710050986769 -0.39764140744405435]]
